

/*
   -- New project --
   
   To compile this code using RemoteXY library 4.1.8 or later version 
   download by link http://remotexy.com/en/library/
   To connect using RemoteXY mobile app by link http://remotexy.com/en/download/                   
     - for ANDROID 4.18.03 or later version;
     - for iOS 1.14.1 or later version;
    
   To interact with the GUI, please refer to the manual: 
   https://remotexy.com/ru/help/code/interaction/

   This source code was automatically generated by the RemoteXY editor and 
   is an example for the RemoteXY library. 
   Licensed under the MIT License. See the LICENSE file in the RemoteXY library
   root (https://github.com/RemoteXY/RemoteXY-Arduino-library) for full license 
   details.             
*/

//////////////////////////////////////////////
//        RemoteXY include library          //
//////////////////////////////////////////////

// you can enable debug logging to Serial at 115200
//#define REMOTEXY__DEBUGLOG    

// RemoteXY select connection mode and include library 
#define REMOTEXY_MODE__ESP32CORE_BLUETOOTH
// definiciones de las librerias a usar 
#include <BluetoothSerial.h>
#include <EEPROM.h>
#include <ESP32Servo.h>
#include <Arduino.h>
#include <Adafruit_PWMServoDriver.h>
#include <Wire.h>

// se crea el pca para poder usarlo
Adafruit_PWMServoDriver pca9685 = Adafruit_PWMServoDriver(0x40);

// RemoteXY connection settings 
#define REMOTEXY_BLUETOOTH_NAME "Robert"
#define REMOTEXY_ACCESS_PASSWORD "1234"


#include <RemoteXY.h>

// RemoteXY GUI configuration  
#pragma pack(push, 1)  
uint8_t const PROGMEM RemoteXY_CONF_PROGMEM[] =   // 135 bytes V21 
  { 254,6,0,0,0,0,0,4,0,2,1,0,3,1,0,4,1,0,5,1,
  0,112,0,21,0,0,0,82,111,98,101,114,116,0,8,2,106,200,200,92,
  1,1,6,0,1,51,39,52,52,171,64,25,25,0,36,31,65,86,65,78,
  90,65,82,0,1,50,137,54,54,171,34,25,25,0,204,31,82,69,84,82,
  79,67,69,68,69,82,0,4,17,107,6,78,61,35,15,51,32,64,26,4,
  48,80,8,111,9,35,15,51,32,64,26,4,49,85,8,111,36,35,15,51,
  32,64,26,4,50,89,8,111,90,35,15,51,32,64,26 };
  
// this structure defines all the variables and events of your control interface 
struct {

    // input variables
  uint8_t Avanzar; // =1 if button pressed, else =0, from 0 to 1
  uint8_t Retroceder; // =1 if button pressed, else =0, from 0 to 1
  int8_t ServoDer1; // from -100 to 100 Servo Derecho de Adelante
  int8_t ServoIzq1; // from -100 to 100 Servo Izquierdo de Adelante
  int8_t ServoIzq2; // from -100 to 100 Servo Izquierdo de Atras
  int8_t ServoDer2; // from -100 to 100 Servo Derecho de Atras

} RemoteXY;   
#pragma pack(pop)
 
/////////////////////////////////////////////
//           END RemoteXY include          //
/////////////////////////////////////////////

// Defincion de pines para el puente H
const int IN1 = 27;
const int IN2 = 26;
const int IN3 = 25;
const int IN4 = 33;

// llamado de funciones 
void avanzar();
void retroceder();
void parar();

// Definicion de Valores de pwm para el servo 
#define SERVOMIN  80  // Minimum value
#define SERVOMAX  600  // Maximum value

// Definicion de lugares de los servomotores en el PCA
#define SER0  0   //Servo Motor 0 on connector 0
#define SER1  4  //Servo Motor 1 on connector 4
#define SER2  12  //Servo Motor 0 on connector 12
#define SER3  15   //Servo Motor 0 on connector 15



void setup() 
{
  RemoteXY_Init ();  // initialization by macros 
  EEPROM.begin(RemoteXYEngine.getEepromSize()); // init EEPROM
  // Definciones de pines del puente h como salida
  pinMode(IN1, OUTPUT);
  pinMode(IN2, OUTPUT);
  pinMode(IN3, OUTPUT);
  pinMode(IN4, OUTPUT);
   // Initialize PCA9685
  Wire.begin();
  pca9685.begin();  

  // Set PWM Frequency to 50Hz
  pca9685.setPWMFreq(50);
  // Se llama a la funcion parar para que los motores parados por las dudas 
  parar();
}

void loop() 
{ 
    RemoteXYEngine.handler ();   
    // se pasan los valores del slider a valores de pwm para manejar el servomotor
    int pwm0 = map(RemoteXY.ServoDer1, -100, 100, SERVOMIN, SERVOMAX);// TODO you setup code
    int pwm1 = map(RemoteXY.ServoDer2, -100, 100, SERVOMIN, SERVOMAX);// TODO you setup code
    int pwm2 = map(RemoteXY.ServoIzq1, -100, 100, SERVOMIN, SERVOMAX);// TODO you setup code
    int pwm3 = map(RemoteXY.ServoIzq2, -100, 100, SERVOMIN, SERVOMAX);// TODO you setup code

    // se mueven los servos
    pca9685.setPWM(SER0, 0, pwm0);
    pca9685.setPWM(SER1, 0, pwm1);
    pca9685.setPWM(SER2, 0, pwm2);
    pca9685.setPWM(SER3, 0, pwm3);
    
    // condicion donde segun se toque el boton de avanzar se mueva el motor o si se toca el boton de retroceder
    // si se toca el de avanzar y no el de retroceder avanza
    if (RemoteXY.Avanzar == 1 && RemoteXY.Retroceder == 0){
        avanzar();// TODO you loop code
    }
    // Si no toca tocado el de avanzar y si el de retorceder, el auto retrocede
    else if(RemoteXY.Avanzar == 0 && RemoteXY.Retroceder == 1){
      retroceder();
    }
    // Si no se toca ninguno de los 2 no retreoceder
    else{
      parar();
    }
  
        // use the RemoteXY structure for data transfer
  // do not call delay(), use instead RemoteXYEngine.delay() 
}

// funcion para avanazar donde se activa los in1 y in3 en high 
void avanzar(void){
    digitalWrite(IN1, HIGH);
    digitalWrite(IN2, LOW);
    digitalWrite(IN3, HIGH);
    digitalWrite(IN4, LOW);
}

// funcion para retroceder donde se activa los in2 y in4 en high 
void retroceder(void){
    digitalWrite(IN1, LOW);
    digitalWrite(IN2, HIGH);
    digitalWrite(IN3, LOW);
    digitalWrite(IN4, HIGH);  
}

// Para los motores poniendo todo en low
void parar(void){
    digitalWrite(IN1, LOW);
    digitalWrite(IN2, LOW);
    digitalWrite(IN3, LOW);
    digitalWrite(IN4, LOW);  

}

